### ISSUE TITLE
Unable to get this to work. Please help!

### ISSUE THREAD

**Issue by teamsuperavis** [nttoanbrvt/WPES-Envato-Theme-Update#1]
Hi

I'm trying to integrate this into my theme but for some reason I'm unable to get it to work. I'm testing it before including this into my next theme update at Envato.

Here's what I've done so far:

- included `wpes-envato-theme-update.php`.
- Added the following code in my `functions.php`.
```php
if( ! function_exists( 'update_my_theme' ) ) {
  function update_my_theme() {
      if( class_exists( 'WPES_Envato_Theme_Update' ) ) {
        $purchase_code = 'xxxxx';
        $personal_access_token = 'xxxxx';
        new WPES_Envato_Theme_Update( basename( get_template_directory() ) , $purchase_code , $personal_access_token, true );
      }
  }
  add_action( 'init' , 'update_my_theme' );
}
```
I'm using original `$purchase_code` and `$personal_access_token` that one of my buyer shared with me in order to test this feature.
- `$purchase code` is in this format xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.
- `$personal_access_token` is 32 characters long string of random alphanumeric characters which was generated from *Buyer's Envato Account* > *Settings* > *API Keys*.
- I have turned on debugging but no messages appear on my screen. So, I have no clue what's wrong.

My WordPress theme at Envato is currently **v1.0.0**. I'm trying to test this update feature by reducing the version of theme installed in my WordPress at *localserver* to **v0.9.0**.

Please let me know what am I missing. Thank you!

**Comment by nttoanbrvt** [comment]
The Personal Token permission must allow you to verify the purchase and downloading the purchase file, for surely, you must ask your buyer to tick on all Required permissions checkboxes.

Otherwise you may remove the update_themes transient for working immediately or wait until the transient is expired.

https://wordpress.org/plugins/transients-manager/

Note: the class requires PHP 5.3.0 or higher for working properly.

**Comment by teamsuperavis** [comment]
Are the *Personal Token* and *API Key* (Envato Account > Settings > API Keys) are the same thing? If no, then where can my buyer find his *Personal Token*? 

Also, where can my buyer find required permissions checkboxes that he must tick?

**Comment by nttoanbrvt** [comment]
The Personal Token and API Key are different, the API key is old and would be retired in future (just my opinion).

As Theme Author, I believe that you know how to talk to your buyer for getting a Personal Token here https://build.envato.com/my-apps/

Have you seen the "Create a new token" button at the end of that page?

**Comment by teamsuperavis** [comment]
Dang! I was not familiar with *Personal Token*. I assumed it the same thing as *API Key*. I asked my buyer to create a Personal Token from the link you sent and now the update feature is working as intended.

Thank you so much for sharing the class you wrote for theme updates and helping me figuring this out.

I would like to mention you in the Credits section of my theme description. Could you please share your  name and perhaps your website?

**Comment by nttoanbrvt** [comment]
Glad to know that helped, that's my pleasure.

I'm here http://themeforest.net/user/phpface or http://phpface.net

Cheers.
