### ISSUE TITLE
Token Permissions

### ISSUE THREAD

**Issue by superavis** [nttoanbrvt/WPES-Envato-Theme-Update#2]
Hi Toan,

Does a buyer need to tick all *Permissions* while generating a *Personal Token*? I was writing about this in my theme's documentation. If ask my buyers to tick all Permission, even the ones that are not needed by theme updates to work, they might have security concerns.

I tried to figure this out by asking my buyer to untick the ones which I think are not needed. I have to ask my buyer to make changes in permissions via email again and again. And I don't want to test his patience with this.

Could you please let me know which specific *Permissions* does the *Personal Token* need to have in order to theme updates to work?

Thanks
Rahul

**Comment by nttoanbrvt** [comment]
The Required permissions should be "Download your purchased items" and "View your purchases of the app creator's items".

**Comment by superavis** [comment]
Thank you so much!

[Here's the link to my theme](http://themeforest.net/item/avocet-responsive-wordpress-blog-theme/13851747). I have mentioned you in Credits :)
