### ISSUE TITLE
Them update is not working when Child Theme is activated

### ISSUE THREAD

**Issue by superavis** [nttoanbrvt/WPES-Envato-Theme-Update#3]
I have theme update class in my theme and it works perfectly there. But it does not work when a child theme is activated.even though I have added purchase code and personal token in the theme options of the child theme.

**Comment by superavis** [comment]
Is there any way to fix this?

**Comment by nttoanbrvt** [comment]
V1.1 is pushed, now it works on child theme too.

**Comment by rahulnever2far** [comment]
Thank you so much!

**Comment by superavis** [comment]
Thank you so much!
